using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;

namespace ProjectEuler.Problems
{
    public class Problems_026_To_050
    {
        //public static string Problem026()
        //{
        //    Console.WriteLine("\n\n\n26. ");

        //    return null;
        //}

        //public static string Problem027()
        //{
        //    Console.WriteLine("\n\n\n27. ");

        //    return null;
        //}

        public static string Problem028()
        {
            Console.WriteLine("\n\n\n28. ");

            return null;
        }

        public static string Problem029()
        {
            Console.WriteLine("\n\n\n29. How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?");

            HashSet<BigInteger> terms = new HashSet<BigInteger>();

            for (int a = 2; a < 101; a++)
            {
                for (int b = 2; b < 101; b++)
                {
                    terms.Add(BigInteger.Pow(a, b));
                }
            }

            return terms.Count.ToString(); ;
        }

        //public static string Problem030()
        //{
        //    Console.WriteLine("\n\n\n30. ");

        //    return null;
        //}

        //public static string Problem031()
        //{
        //    Console.WriteLine("\n\n\n31. ");

        //    return null;
        //}

        //public static string Problem032()
        //{
        //    Console.WriteLine("\n\n\n32. ");

        //    return null;
        //}

        //public static string Problem033()
        //{
        //    Console.WriteLine("\n\n\n33. ");

        //    return null;
        //}

        //public static string Problem034()
        //{
        //    Console.WriteLine("\n\n\n34. ");

        //    return null;
        //}

        //public static string Problem035()
        //{
        //    Console.WriteLine("\n\n\n35. ");

        //    return null;
        //}

        //public static string Problem036()
        //{
        //    Console.WriteLine("\n\n\n36. ");

        //    return null;
        //}

        //public static string Problem037()
        //{
        //    Console.WriteLine("\n\n\n37. ");

        //    return null;
        //}

        //public static string Problem038()
        //{
        //    Console.WriteLine("\n\n\n38. ");

        //    return null;
        //}

        //public static string Problem039()
        //{
        //    Console.WriteLine("\n\n\n39. ");

        //    return null;
        //}

        //public static string Problem040()
        //{
        //    Console.WriteLine("\n\n\n40. ");

        //    return null;
        //}

        //public static string Problem041()
        //{
        //    Console.WriteLine("\n\n\n41. ");

        //    return null;
        //}

        //public static string Problem042()
        //{
        //    Console.WriteLine("\n\n\n42. ");

        //    return null;
        //}

        //public static string Problem043()
        //{
        //    Console.WriteLine("\n\n\n43. ");

        //    return null;
        //}

        //public static string Problem044()
        //{
        //    Console.WriteLine("\n\n\n44. ");

        //    return null;
        //}

        //public static string Problem045()
        //{
        //    Console.WriteLine("\n\n\n45. ");

        //    return null;
        //}

        //public static string Problem046()
        //{
        //    Console.WriteLine("\n\n\n46. ");

        //    return null;
        //}

        //public static string Problem047()
        //{
        //    Console.WriteLine("\n\n\n47. ");

        //    return null;
        //}

        //public static string Problem048()
        //{
        //    Console.WriteLine("\n\n\n48. ");

        //    return null;
        //}

        //public static string Problem049()
        //{
        //    Console.WriteLine("\n\n\n49. ");

        //    return null;
        //}

        //public static string Problem050()
        //{
        //    Console.WriteLine("\n\n\n50. ");

        //    return null;
        //}
    }
}